## 1. Import Library

In [2]:
import numpy as np

### Penjelasan Kode

+ Baris ini mengimpor library NumPy dengan alias np.
+ Alias ini digunakan agar lebih ringkas ketika memanggil fungsi, misalnya np.array() dibandingkan numpy.array().

### Fungsi Library

NumPy adalah library Python yang digunakan untuk komputasi numerik. Dengan NumPy, kita bisa membuat array, melakukan operasi matematika, manipulasi data, hingga analisis data numerik dengan sangat cepat dan efisien.

---

## 2. Membuat Array dari List

In [3]:
# membuat array dengan numpy
mylist = [1, 2, 3]
myarray = np.array(mylist)
print(type(mylist))
print(type(myarray))
print(myarray.shape)
print(myarray)

<class 'list'>
<class 'numpy.ndarray'>
(3,)
[1 2 3]


### Fungsi Library
Pada block ini, fungsi np.array() dari NumPy digunakan untuk mengonversi list Python menjadi array NumPy. Dengan array ini, data lebih mudah diproses secara matematis dan lebih efisien dibandingkan list Python.

### Penjelasan Kode
Program ini pertama membuat sebuah list Python biasa bernama mylist. Kemudian, list tersebut diubah menjadi NumPy array menggunakan np.array(). Setelah itu, program menampilkan tipe data list (<class 'list'>) dan tipe data array (<class 'numpy.ndarray'>), bentuk array ((3,) yang berarti 1 dimensi dengan 3 elemen), serta isi array [1 2 3].

___

## 3. Membuat Array 2 Dimensi Operasi Aritmatika

In [ ]:
# access data pada numpy array
mylist = [[1, 2, 3], [4, 5, 6]]
myarray = np.array(mylist)

print(myarray)
print(myarray.shape)
print("Baris pertama:", myarray[0])
print("Baris terakhir:", myarray[-1])
print("Baris pertama kolom ketiga:", myarray[0][2])
print("Hasilnya:", myarray[:, 2])


[[1 2 3]
 [4 5 6]]
(2, 3)


In [86]:
# operasi aritmatik pada numpy array
myarray1 = np.array([2, 2, 2])
myarray2 = np.array([3, 3, 3])

print("Perjumlahan array:", myarray1 + myarray2)
print("Perkalian array:", myarray1 * myarray2)

Perjumlahan array: [5 5 5]
Perkalian array: [6 6 6]


### Penjelasan Kode
Pada bagian pertama, kode membuat array 2 dimensi (2x3) dari list bersarang [[1,2,3],[4,5,6]]. Array ini kemudian ditampilkan beserta bentuknya (2,3), yang berarti 2 baris dan 3 kolom. Program juga mendemonstrasikan indexing:

- Mengambil baris pertama ([1 2 3]).

- Mengambil baris terakhir ([4 5 6]).

- Mengambil elemen baris pertama kolom ketiga (3).

- Mengambil seluruh elemen di kolom ketiga ([3 6]).

Pada bagian kedua, dibuat dua array 1 dimensi myarray1 dan myarray2. Kemudian dilakukan operasi aritmatika element-wise:

- Penjumlahan [2 2 2] + [3 3 3] = [5 5 5].

- Perkalian [2 2 2] * [3 3 3] = [6 6 6].

### Fungsi Library

Di block ini, NumPy digunakan untuk:

1. Membuat array 2D yang memungkinkan penyimpanan data berbentuk tabel/matriks.
2. Melakukan indexing (mengakses baris, kolom, atau elemen tertentu dalam array).

3. Menjalankan operasi aritmatika vektorized (penjumlahan dan perkalian langsung antar array tanpa loop manual).